<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Nikki" failures="1" tests="6" name="org.smokeandregressionretryasanalyser.test.Class1Practice" time="24.174" errors="0" timestamp="2022-08-19T16:01:31 IST" skipped="3">
  <testcase classname="org.smokeandregressionretryasanalyser.test.Class1Practice" name="test2" time="4.008"/>
  <system-out/>
  <testcase classname="org.smokeandregressionretryasanalyser.test.Class1Practice" name="test3" time="6.015"/>
  <system-out/>
  <testcase classname="org.smokeandregressionretryasanalyser.test.Class1Practice" name="test1" time="3.308">
    <failure message="The following asserts failed:
	expected [B] but found [A]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [B] but found [A]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at org.smokeandregressionretryasanalyser.test.Class1Practice.test1(Class1Practice.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="org.smokeandregressionretryasanalyser.test.Class1Practice" name="test1" time="2.951">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="org.smokeandregressionretryasanalyser.test.Class1Practice" name="test1" time="4.191">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="org.smokeandregressionretryasanalyser.test.Class1Practice" name="test1" time="3.701">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
</testsuite> <!-- org.smokeandregressionretryasanalyser.test.Class1Practice -->
